### ISSUE TITLE
Hi, could you kindly give exapmle or teach or how can i implement this same thing for windows?

### ISSUE THREAD

**Issue by pyhtonlovertytt** [rdbo/cstrike-bhop-in-linux#1]
It's so good to see your own hooking library that u mad.How can I use this same base for windows? like implement createmove hook in it and do aimbot and triggerbot stuff.

**Comment by rdbo** [comment]
This is want you want, there's everything there:
https://www.youtube.com/user/L4DL4D2EUROPE
https://guidedhacking.com/
There are plenty of tutorials on hacking CS Source and CSGO, and they're applicable to CS 1.6
If you do the tuts, read the threads and spend enough time game hacking, eventually you'll be able to do anything you want with the target game.
And yes, you can use my memory lib for Windows.
C/C++ Version of Memory Lib (working more actively there): https://github.com/rdbo/libmem
C++ Only Version of Memory Lib: https://github.com/rdbo/Memory
